

---
title: Arrays and objects
date: June 8, 2018
output:
    revealjs::revealjs_presentation:
        theme: beige
        transition: default
        center: true
        incremental: true
        slide-level: 0
---

## Recap: primitive data types

### Numbers, booleans and strings are primitive data types.

* Numbers have numeric values
* Booleans have two values: true and false
* Strings are text, wrapped in `""` and `''`.

### There are also two special primitive data types, `null` and `undefined`.

## Recap: Bindings.
* Bindings are defined with *let*, *const* and *var*
* Bindings defined with *const* always point to the same value
* *let* was introduced in ES-2015 and replaced *var*

```javascript
const x = 10;
let y = 20;
y = 20;
let n = "Something", q = "Another thing"
```

## Recap: Functions.
* Functions are "subprograms" that can be called by code.
* Function is composed from number of statements
* Functions can have parameters and the function will *return* a value
* Functions can return a function

```javascript
function square(x) {
    return x * x
}
```
# Numbers, booleans and strings are the foundation upon which the data structures are built on.

## To work with data wee need a way to represent it in our machine's memory. Let's say we want to represent collection of words Yerevan, Gyumri, Vanadzor, Spitak, Ashtarak.

### JavaScript provides a way to store not a single but a sequence of values. It's called `array`.

```javascript
const cities = ["Yerevan", "Gyumri", "Vanadzor", "Spitak", "Ashtarak"]
```

### Every element in an array is given an index. Indexation starts from `0`, not `1`

## Properties
> There are expressions which access a **property** of some value. Properties have names and values.

```javascript
let array = [1,2,3]
array.length // length is a property of Array.
let string1 = "Length"
string1.length
```

### We can access properties with a `dot` and with `square brackets`

## Accessing properties with 'dot'

> When accessing the property with a dot, the part after it should be a valid binding name. So we are `naming` the property.

```javascript
const cities = ["Yerevan", "Ashtarak", "Vanadzor"]
console.log(cities.length) // -> 3
```

## Accessing properties with bracket

> When accessing the property with brackets, the expression between them is `evaluated` to get the property name.

```javascript
const cities = ["Yerevan", "Ashtarak", "Vanadzor"]
console.log(cities["length"]) // -> 3
```


## Methods.
> Methods are the **properties** which hold function values

```javascript
console.log("JS is fun")
const city = "Yerevan"
const upperCaseCity = city.toUpperCase()
console.log(upperCaseCity) // -> "YEREVAN"
```

 **toUpperCase** is a **method** on string. It returns a copy of the original string, with all letters converted to uppercase

## Objects allow us to group other values.
### Values of the type *object* are arbitrary collection of properties.

```javascript
let work = {
    developer: true,
    tech_stack: [js, python, rust],
    position: "Senior"
}

console.log(work.developer) // true
```

##

### If we try to access a value which does not exist, the undefined value will be produced.

### We can assign a value to a property by using the = operator.

#### This will replace the property’s value if it already existed or create a new property on the object if it didn’t.

```javascript
let work = {
    developer: true,
    tech_stack: [js, python, rust],
    position: "Senior"
}

console.log(work.position) // -> Senior
console.log(work.salary) // -> undefined

work.salary = 1000000000000000

console.log(work.salary) // -> 1000000000000000
```

## Object operators

We can use the `delete` operator to delete remove a property from the object.

```javascript
const obj = {first: 1, second: 2}

conosle.log(obj.first) // -> 1

delete obj.first

console.log(obj.first) // -> undefined
console.log("first" in obj ) // -> false
console.log("second" in obj) // -> true
```

> ***in***  is a binary operator, that indicates weather the given object has the property or not.

## ARRAYS ARE OBJECTS TOO

> Arrays are objects, which are specialized for storing sequences of data.

#

## Write a function, which will take an *array* as argument, and for each element log. "This is 1st", "This is 2nd", "This is 3rd" etc.

