
---
title: Introduction to JavaScript, Functions
date: June 6, 2018
output:
    revealjs::revealjs_presentation:
        theme: beige
        transition: default
        center: true
        incremental: true
        slide-level: 4
---

## Functions
### Function is a binding where the value is a function
Functions are created with *function* keyword.

```javascript
const greet = function(name) {
    console.log(name)
}

greet("Artavazd");

```

Functions have *parameters* and *body*.
A *return* statement in the function determines a *value* that function returns.
Functions that don't have *return* will return *undefined*

## Write a function `power`, where user can pass `base` and `exponent` as arguments and get result.
### For example: power(5, 2) returns 25.

```javascript
cosnt power = function(base, exponent) {
    let result;
    for(.....) {
        ....
    }
    return result;
}

```


## Scopes
### Bindings have scopes: part of the program where the bindings are visible.

```javascript
const multiply = function (x) {
    let y = 10;
    console.log(y) // 10
    return x * 10
}
console.log(y) // not defined
```
 Here the `y` is `local` to function `multiply` and we can't access it anywhere outside of the function's `scope`

## Let and Const
### Bindings declared with *let* and *const* are local to the *block*

```javascript
let y = 0;
let n = 5;
if(true) {
  console.log(n)
  var x = 10;
  let y = 20;
  console.log(y)
}
console.log(y, 'y')
```

## Declaration
### A shorter way to create a function binding

```javascript
greet("Artavazd");

function greet(name) {
    console.log(name)
}
```
This is called a function declaration

## Arrow function
### In ES2015 the new way of declaring functions was introduced.

```javascript
const greet = (name) => {
    return console.log(name)
}
//same as
const greet = name => console.log(name)
```

## Call Stack

```javascript
const exclaim = (word) => {
    let mark = ' !'
    console.log(word.toUpperCase + mark)
}

exclaim("Hello")
```

### What's happening ?

#### The computer needs to remember the context from which the call happened.

> The place where computer stores this context is called **call stack**

## Arguments

JavaScript doesn't complain if you pass wrong number of arguments.

Extra arguments will be ignored, and missing arguments will be assigned value of **undefined**

```javascript
function square(x) { return x * x }
square(9, 'something', 3) // returns 81

// Downside
function add(x, y) {
    return x + y
}

add(3) // returns NaN

// You can pass default value if needed

function add(x, y = 1) { return x + y }
add(2) // returns 3
```

## Closures

### What happens to local bindings when the function call that created them is no longer active?


```javascript
function value(x) {
    let scoped = n;
    return () => scoped
}

let newValue1 = value(1)
let newValue2 = value(2)

newValue1()
newValue2()

// What  will happen ?

```

***Note, in function `value` we return a new `function`***

## Write a function `multiply` which will take argument factor, return another `function` taking argument `number` and multiplying it by factor.

```javascript

function multiply(factor) {
    return // function taking argument number and multiplying it by factor
}

const twice = multiply(2) // type of twice ?
twice(10) // should return 20
```

## Recursion
### Functions can also call themselves. Such function is called *recursive*.
Using recursion we can write functions in a different style. For example the *power* function can be rewritten using recursion.

```javascript
function power(base, exponent) {
    if(exponent == 0) {
        return 1;
    }
    else {
        return base * power(base, exponent - 1)
    }
}
```


## Write calculator functions.

> - `squareNumber` which takes on argument as a number and returns it's square. E.g squareNumber(5) returns 25.
> - `half` which takes one argument and divides it by 2.
> - `percent` which takes two arguments and returns what percent the first number represents of the second number. E.g percent(10, 100) returns 10 is 10% of 100.
