---
title: Introduction to JavaScript, Values and Types
date: June 4, 2018
output:
    revealjs::revealjs_presentation:
        theme: black
        transition: fade
        center: true
        incremental: true
        slide-level: 4
---

## JavaScript
<h4> High-level, interpreted  programming language </h4>

## How computer sees it
<h4> Everything is data, stored as long sequences of bits (0,1) </h4>

```
   0   0   0   0   0   1   0   1
 128  64  32  16   8   4   2   1
```

## Values
<h4>Billions and billions of bits </h4>
To be able to manipulate such amount of bits we must separate them into chunks, or ***Values***

## Every Value Has a Type.
#### Some are numbers, some are functions etc.

# Numbers

## Numbers in JavaScript are numeric values

For example:

```{js}
8 //integer
3.4 //fraction
e //exponent
```

## Arithmetics
### Take two values and produce one

```{js}
25 * 4 = 100
```

The symbol `*` is called *operator*

*Note: Not all operators are symbols, some are written as words. These are called <b>unary operators</b>*

## Special Numbers
**Infinity, -Infinity, NaN**

*Nan stands for 'Not a Number', but has type of number*

# Strings

## *string* data type represents text. They are written as follows

```{js}
"Hello World!"
'This is also valid'
`Backtiks can be used too` \\ Also called *template literals*
```
## Strings can be 'added'
Addition of the strings together is called *concatenation*

```{js}
"Hello" + "World" / "HelloWorld"
```

# Booleans

## Boolean values are used to distinguish between two possibilities.

### JavaScript has boolean type, which has two values *true* and *false*.

```{js}
5 > 2 //true
"Three" == 3 //false
```

## Logical Operators

JavaScript has three logical operators: *and* *or* and *not*

## AND (&&)
### AND operator returns `true` only if both operands are true.

| Value 1 | Value 2 | Returns |
|:--------|:--------|:--------|
| true | true | true |
| true | false | false |
| false | false | true |

## OR (||)
### Or operator returns *false* only when two false operands are compared

| Value 1 | Value 2 | Returns |
|:--------|:--------|:--------|
| true | true | true |
| true | false | true |
| false | false | false |

## NOT (!)
### Not operator returns the 'opposite' of the operand

`!true` - returns `false`

`!false` - returns `true`

`!'str'` - returns `false`


# Empty Values

## `Null` and `undefined` are two special values used to denote the absence of a `meaningful` value

### To put simply, these are values carrying no information.


# Type coercion.

## Type coercion is just a fancy word to describe type conversion.

```{js}
8 * null
// → 0
console.log("5" - 1)
// → 4
console.log("5" + 1)
// → 51
console.log("five" * 2)
// → NaN
console.log(false == 0)
// → true
```

# How to interact with values.

## Expressions and Statements
### Part of the code that produces value is an *expression*

```{js}
false
14
'string'
```
### List of *expressions* is a *statement*

## Variables

### Variable or binding is a way for computer to catch and hold values

```{js}
let ten = 5 * 2;
ten * 10;
```
The *keyword* `let` indicates that above statement defines a binding.

One `let` statement can define multiple bindings
```{js}
let money = 100, debt = 20;
```

## The binding is not necessarily tied to the assigned value

```{js}
let name = "Armen";
console.log(name) // -> Armen
name = "Karen";
console.log(name) // -> Karen
```
### What will happen if the binding is defined without a given value ?

## Let, Var, and Const
### Var stands for variable and const stands for constant.
`var` is the way of binding used before 2015 JavaScript.
`const` defines a constant binding which points to the same value

```{js}
var tale = "A tale of two cities";
const city = "Yerevan";

tale = "New Tale"; // this is ok
city = "Tbilisi"; // TypeError.
```

## What can be used as a name for binding

Any word can be a binding name, numbers also. However the name should not start with number.
Binding name can also contain `$` and `_` but no special characters and punctuation marks. Keywords cannot be used as well.

## There are some bindings which are part of the language standard or environment.

## Functions

### `function` is a piece of program which has value. Values are called to run the program.
Functions are called by putting parenthesis after an expression

```{js}
console.log("Greetings")
```
For example: `console.log()` is a predefined value provided by the environment. The values between the parentheses are given to the program inside the function, and are called `arguments`

##

Functions can require arguments  of different amount and different types.

## Flow

In JavaScript program is executed from top to bottom.
Without any conditionals in the code, the `control flow` is straight.

## Conditionals

### Not all programs have straight control flow. We may want the program to respond differently in certain conditions.

Conditional in JavaScript are created with `if` keyword. `if` Evaluates the boolean output.

```{js}
const x = 10;
const y = 20;
if (x < y) {
    console.log("20 is greater than 10")
}
```

Braces can be used to group number of statements.

## Loops

### In JavaScript we have three loops, `while` `do` and `for` loops.


## For loop

### Many loops have similar patterns as `while` loops. First counter is created, then comes a while loop that checks if the counter has reached needed value, and at the end counter is updated.
So, for the sake of simplicity JS and other languages provide simpler `for` loop.

