---
title: Web
date: June 15, 2018
output:
    revealjs::revealjs_presentation:
        theme: black
        transition: slide
        center: false
        incremental: true
        slide_level: 1
        self_contained: false
        reveal_plugins: ["zoom"]
---

# Browsers

### Browsers are the reason we have JavaScript today.

The ideological foundation of the web is it's being decentralized. Different browser companies have added different functionalities. This has both pros and cons.

# The Internet

## Internet is one of the most amazing technologies that we have. It's truly astonishing what can be done by connecting computers with cables.

> Essentially, it's just sending sequences of bits to each other, and making other computers to understand what these sequences represent. But how to make them to do so ?

# Meet Protocols

> `Network Protocol` sets the style of communication between computers.

There are bunch of protocols that we use daily. They are used to send and get emails, share files, control other computer in a network and so on. We will cover them more as we move on.

# The Web

> The World Wide Web (not to be confused with the Internet as a whole) is a set of protocols and formats that allow us to visit web pages in a browser

Each document on the web has a name: URL (`Uniform Resource Locator` ).

```
   http://grdon.solutions/grdon.html
protocol |     server    | path to file
```

# IP

#### Machines that connect to the internet get an IP address, which is a number that's used by other computers to communicate with us.

However accessing a computer with IP address doesn't look nice. That's why we use `domain names`

```
216.58.206.206 vs google.com
```

`google.com` points to the mentioned IP address in the web.

# HTML

> HTML ( Hypertext Markup Language) is the standard format used for web pages.

As any markup language, it has a content wrapped in `tags` that structure the content.

```html
<html>
    <head>
        <meta charset='utf-8'>
        <title> My Page </title>
    </head>
    <body>
        <h1> Hello to my home page </h1>
        <p> This is a paragraph </p>
        <a href="grdon.solutions"> My other website </a>
    </body>
</html>
```

# Hello from JavaScript

We can also include JavaScript in our HTML page with `<script>` tag.

```html
<p> Here comes prompt </p>
<script> prompt("I told you so") </script>
```

Of course, including large chunks of JavaScript in such manner is impractical. That's why we can give a link to .js inside a script tag, with `src` attribute.

```html
<script src="./prompt.js"></script>
```

# Browsers

### So what happens when the browser reads the .html file ?

>The browser builds up a model of the document’s structure and uses this model to draw the page on the screen.

# Document Structure

### We can imagine the document as nested boxes.

```html
<html>
    <head>
        <title> My page </title>
    </head>
    <body>
       <h1> Hello </h1>
       <p> My Paragraph </p>
    </body>
</html>
```

# DOM

> The data structure that browsers use to represent the .html document has similar shape.  For each box, there is an object, which we can interact with. This representation is called the Document Object Model, or DOM.

There is a global `document` binding which allows us to interact with those objects
